name: ModPersonServiceDeno
on:
  push:

jobs:
  personservice:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: sgohlke/workflows/.github/workflows/deno.yml@main
      - name: Get tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_version
        run: echo TAG_VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: npm build
        run: deno run -A ./scripts/build_npm.ts ${{steps.get_tag_version.outputs.TAG_VERSION}}
