name: ModPersonServiceDeno
on: 
  push:

jobs:
  rpgts:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: '1.13.2'
      - run: deno lint --unstable
      - run: deno test
